version: '3.3'
services:
  db:
    image: postgres:15.3-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starsmap

  gateway:
    image: sobiy/starsmap_gateway:latest
    volumes:
      - static:/var/html/static
    ports:
      - 8000:80
    depends_on:
      - web

  web:
    image: sobiy/starsmap:latest
    restart: always
    volumes:
      - static:/app/staticfiles/
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  static:
