openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/team/:
    get:
      operationId: listTeams
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
          description: ''
      tags:
      - api
  /api/v1/team/{id}/:
    get:
      operationId: retrieveTeam
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041A\u043E\u043C\u0430\
          \u043D\u0434\u0430."
        schema:
          type: string
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: ''
      tags:
      - api
  /api/v1/competence/:
    get:
      operationId: listCompetences
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competence'
          description: ''
      tags:
      - api
  /api/v1/competence/{id}/:
    get:
      operationId: retrieveCompetence
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041A\u043E\u043C\u043F\
          \u0435\u0442\u0435\u043D\u0446\u0438\u044F."
        schema:
          type: string
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Competence'
          description: ''
      tags:
      - api
  /api/v1/skill/:
    get:
      operationId: listSkills
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      - name: domain
        required: false
        in: query
        description: domain
        schema:
          type: string
          enum:
          - Hard skills
          - Soft skills
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
          description: ''
      tags:
      - api
  /api/v1/skill/{id}/:
    get:
      operationId: retrieveSkill
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041D\u0430\u0432\u044B\
          \u043A."
        schema:
          type: string
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      - name: domain
        required: false
        in: query
        description: domain
        schema:
          type: string
          enum:
          - Hard skills
          - Soft skills
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
          description: ''
      tags:
      - api
  /api/v1/rating/:
    get:
      operationId: listRatings
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Raiting'
          description: ''
      tags:
      - api
  /api/v1/rating/{id}/:
    get:
      operationId: retrieveRating
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0420\u0435\u0439\u0442\
          \u0438\u043D\u0433."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Raiting'
          description: ''
      tags:
      - api
  /api/v1/lastrating/:
    get:
      operationId: listLastRatings
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LastRating'
          description: ''
      tags:
      - api
  /api/v1/lastrating/{id}/:
    get:
      operationId: retrieveLastRating
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041E\u0446\u0435\u043D\
          \u043A\u0430 \u043D\u0430\u0432\u044B\u043A\u043E\u0432."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LastRating'
          description: ''
      tags:
      - api
  /api/v1/user/:
    get:
      operationId: listUsers
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/v1/user/{id}/:
    get:
      operationId: retrieveUser
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u043E\u0442\u0440\
          \u0443\u0434\u043D\u0438\u043A."
        schema:
          type: string
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/v1/candidate/:
    get:
      operationId: listCandidates
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candidate'
          description: ''
      tags:
      - api
  /api/v1/candidate/{id}/:
    get:
      operationId: retrieveCandidate
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041A\u0430\u043D\u0434\
          \u0438\u0434\u0430\u0442."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
          description: ''
      tags:
      - api
  /api/v1/vacancy/:
    get:
      operationId: listVacancies
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: position
        required: false
        in: query
        description: position
        schema:
          type: string
      - name: team
        required: false
        in: query
        description: team
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vacancy'
          description: ''
      tags:
      - api
  /api/v1/vacancy/{id}/:
    get:
      operationId: retrieveVacancy
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043C\u043E\u0434\u0435\u043B\
        \u0438"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0412\u0430\u043A\u0430\
          \u043D\u0441\u0438\u044F."
        schema:
          type: string
      - name: position
        required: false
        in: query
        description: position
        schema:
          type: string
      - name: team
        required: false
        in: query
        description: team
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacancy'
          description: ''
      tags:
      - api
components:
  schemas:
    Team:
      type: object
      properties:
        name:
          type: string
          maxLength: 250
        leader:
          type: string
      required:
      - name
      - leader
    Competence:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 250
      required:
      - name
    Skill:
      type: object
      properties:
        name:
          type: string
          maxLength: 250
        domain:
          enum:
          - Hard skills
          - Soft skills
          type: string
        competence:
          type: string
          readOnly: true
      required:
      - name
      - domain
    Raiting:
      type: object
      properties:
        score:
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          type: integer
        date_score:
          type: string
          format: date
        need_to_study:
          type: boolean
        date_need:
          type: string
          format: date
        date_start:
          type: string
          format: date
        date_end:
          type: string
          format: date
        match:
          type: boolean
        chief_proof:
          type: boolean
    LastRating:
      type: object
      properties:
        skill:
          type: object
          properties:
            name:
              type: string
              maxLength: 250
            domain:
              enum:
              - Hard skills
              - Soft skills
              type: string
            competence:
              type: string
              readOnly: true
          required:
          - name
          - domain
          readOnly: true
        last_match:
          type: boolean
        last_date:
          type: string
          format: date
        rating:
          type: array
          items:
            type: object
            properties:
              score:
                enum:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                type: integer
              date_score:
                type: string
                format: date
              need_to_study:
                type: boolean
              date_need:
                type: string
                format: date
              date_start:
                type: string
                format: date
              date_end:
                type: string
                format: date
              match:
                type: boolean
              chief_proof:
                type: boolean
          readOnly: true
    User:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 250
        last_name:
          type: string
          maxLength: 250
        date_hire:
          type: string
          format: date
        date_fire:
          type: string
          format: date
          nullable: true
        team:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                maxLength: 250
              leader:
                type: string
            required:
            - name
            - leader
          readOnly: true
        position:
          type: string
          readOnly: true
        grade:
          enum:
          - No value
          - Junior
          - Middle
          - Senior
          type: string
        role:
          enum:
          - admin
          - hr
          - team_chief
          - user
          type: string
        key_people:
          type: boolean
        bus_factor:
          type: boolean
        emi:
          type: number
        lastrating:
          type: array
          items:
            type: object
            properties:
              skill:
                type: object
                properties:
                  name:
                    type: string
                    maxLength: 250
                  domain:
                    enum:
                    - Hard skills
                    - Soft skills
                    type: string
                  competence:
                    type: string
                    readOnly: true
                required:
                - name
                - domain
                readOnly: true
              last_match:
                type: boolean
              last_date:
                type: string
                format: date
              rating:
                type: array
                items:
                  type: object
                  properties:
                    score:
                      enum:
                      - 0
                      - 1
                      - 2
                      - 3
                      - 4
                      - 5
                      type: integer
                    date_score:
                      type: string
                      format: date
                    need_to_study:
                      type: boolean
                    date_need:
                      type: string
                      format: date
                    date_start:
                      type: string
                      format: date
                    date_end:
                      type: string
                      format: date
                    match:
                      type: boolean
                    chief_proof:
                      type: boolean
                readOnly: true
          readOnly: true
      required:
      - first_name
      - last_name
    Candidate:
      type: object
      properties:
        link:
          type: string
          format: uri
          nullable: true
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\\
            .(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\\
            ]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1-\uFFFF0-9])?(?:\\\
            .(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
            .?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\s]*)?\\z"
    Vacancy:
      type: object
      properties:
        position:
          type: string
          readOnly: true
        team:
          type: string
          readOnly: true
        closed:
          type: boolean
        candidate:
          type: array
          items:
            type: object
            properties:
              link:
                type: string
                format: uri
                nullable: true
                maxLength: 200
                pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\\
                  .(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\\
                  ]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1-\uFFFF\
                  0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
                  -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\\
                  s]*)?\\z"
          readOnly: true
