# Generated by Django 4.2 on 2024-10-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('No value', 'No value'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default=('No value', 'No value'), max_length=24, verbose_name='Уровень'),
        ),
    ]
