# Generated by Django 4.2 on 2024-10-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_lastrating_date_need_lastrating_need_to_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastrating',
            old_name='date_need',
            new_name='last_date_need',
        ),
        migrations.RenameField(
            model_name='lastrating',
            old_name='need_to_study',
            new_name='last_study',
        ),
    ]
