# Generated by Django 4.2 on 2024-10-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_date_need_lastrating_last_date_need_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastrating',
            old_name='last_date_need',
            new_name='last_date_study',
        ),
        migrations.RenameField(
            model_name='lastrating',
            old_name='last_study',
            new_name='last_need_to_study',
        ),
    ]
