# Generated by Django 4.2 on 2024-10-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastrating',
            name='competence',
        ),
    ]
