# Generated by Django 4.2 on 2024-09-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_last_rating',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='key_people',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('Не оценивался', 'Не оценивался'), ('Не владеет', 'Не владеет'), ('Базовый', 'Базовый'), ('Уверенный', 'Уверенный'), ('Экспертный', 'Экспертный')], default=('Не оценивался', 'Не оценивался'), max_length=13),
        ),
        migrations.AlterField(
            model_name='skill',
            name='domain',
            field=models.CharField(choices=[('Hard skills', 'Hard skills'), ('Soft skills', 'Soft skills')], max_length=12),
        ),
    ]
