# Generated by Django 4.2 on 2024-10-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_lastrating_competence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastrating',
            options={'ordering': ['user', 'skill'], 'verbose_name': 'Соответствие на последнюю дату', 'verbose_name_plural': 'Соответствия на последнюю дату'},
        ),
    ]
