# Generated by Django 4.2 on 2024-09-29 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_date_last_rating_rating_key_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_last_rating',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
