# Generated by Django 4.2 on 2024-10-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_lastrating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
