# Generated by Django 4.2 on 2024-10-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_team_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastrating',
            options={'ordering': ['user', 'skill'], 'verbose_name': 'Оценка навыков', 'verbose_name_plural': 'Оценки навыков'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
